import { NavBar } from '@/components/navbar'
import type { Metadata } from "next"
import { Poppins } from "next/font/google"
import Head from 'next/head'
import "./globals.css"


// Настройка Poppins с нужными начертаниями
const poppins = Poppins({
  weight: ['400', '500', '600', '700'], // Выберите нужные варианты толщины
  subsets: ["latin"],
  variable: "--font-poppins",
  display: 'swap',
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={poppins.className}>
      <Head>
        <script src="https://telegram.org/js/telegram-web-app.js?57" />
      </Head>
      <body style={{ display: 'flex', flexDirection: 'column', minHeight: '100vh' }}>
        <main style={{ flex: '1' }}>
          {children}
        </main>
        <NavBar />
      </body>
    </html>
  );
}